export const mockProducts = [
  {
    id: '1',
    name: 'Wireless Headphones',
    sku: 'TECH-001',
    category: 'Electronics',
    price: 129.99,
    stock: 45,
    description: 'High-quality wireless headphones with noise cancellation',
    active: true,
    createdAt: new Date('2024-10-01'),
    image: '/wireless-headphones.png',
  },
  {
    id: '2',
    name: 'Office Chair',
    sku: 'FURN-001',
    category: 'Furniture',
    price: 249.99,
    stock: 8,
    description: 'Ergonomic office chair with lumbar support',
    active: true,
    createdAt: new Date('2024-10-02'),
    image: '/ergonomic-office-chair.png',
  },
  {
    id: '3',
    name: 'Cotton T-Shirt',
    sku: 'CLOTH-001',
    category: 'Clothing',
    price: 29.99,
    stock: 150,
    description: '100% organic cotton t-shirt',
    active: true,
    createdAt: new Date('2024-10-03'),
    image: '/cotton-t-shirt.jpg',
  },
]

export const mockOrders = [
  {
    id: 'ORD-001',
    clientName: 'John Doe',
    productIds: ['1'],
    quantities: [2],
    totalAmount: 259.98,
    paymentStatus: 'Paid',
    deliveryStatus: 'Delivered',
    deliveryProgress: 100,
    expectedDeliveryDate: new Date('2024-10-15'),
    deliveryAddress: '123 Main St, City, Country',
    customerFeedback: 'happy',
    createdAt: new Date('2024-10-01'),
  },
  {
    id: 'ORD-002',
    clientName: 'Jane Smith',
    productIds: ['2'],
    quantities: [1],
    totalAmount: 249.99,
    paymentStatus: 'Pending',
    deliveryStatus: 'Shipped',
    deliveryProgress: 65,
    expectedDeliveryDate: new Date('2024-10-22'),
    deliveryAddress: '456 Oak Ave, City, Country',
    customerFeedback: 'neutral',
    createdAt: new Date('2024-10-05'),
  },
]
